[package]
name = "rc"
version = "0.1.0"
authors = ["Brad Svercl <bradsvercl@gmail.com>"]

[dependencies]
piston_window = "0.64"
pistoncore-sdl2_window = "*"
rand = "*"
image = "*"
fps_counter = "*"
cgmath = "*"

